apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-route
  namespace: helloworld-ns
  labels:
    razee/watch-resource: lite
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: helloworld-svc
            port:
              number: 8080
        path: "/helloworld"
        pathType: Exact